heatmap.2(hm,
          main = "DPlike(58) vs ASC(89)",
          trace = "none",
          #Colv = T,
          cexRow = 0.2,
          cexCol = 1,
          srtCol=45,
          col = colorRampPalette( rev(brewer.pal(9, "RdBu")) )(11),
          breaks = seq(-1.5,1.5,length.out = 12),
          dendrogram = "row",
          keysize = 1.0,
          key.title = "z-score of log2(count)",
          key.par = list(cex=0.5),
          margins = c(5,5),
          lhei=c(1,5))# ,lwid=c(2,1))